sources:
  - name: AuthService
    handler:
      openapi:
        source: http://auth-service:5001/swagger/v1/swagger.json
  
  - name: UserService
    handler:
      openapi:
        source: http://user-service:5002/swagger/v1/swagger.json
  
  - name: ProductService
    handler:
      openapi:
        source: http://product-service:5004/swagger/v1/swagger.json
  
  - name: CustomerService
    handler:
      openapi:
        source: http://customer-service:5005/swagger/v1/swagger.json
  
  - name: ReportService
    handler:
      openapi:
        source: http://report-service:5007/swagger/v1/swagger.json
  
  - name: NotificationService
    handler:
      openapi:
        source: http://notification-service:5008/swagger/v1/swagger.json

serve:
  port: 4000
  playground: true
  cors:
    origin: "*"
