sources:
  - name: AuthService
    handler:
      openapi:
        source: http://auth-service:5001/swagger/v1/swagger.json
  
  - name: UserService
    handler:
      openapi:
        source: http://user-service:5002/swagger/v1/swagger.json
  
  - name: ProductService
    handler:
      openapi:
        source: http://product-service:5004/swagger/v1/swagger.json
  
  - name: TransactionService
    handler:
      openapi:
        source: http://transaction-service:5006/swagger/v1/swagger.json

serve:
  port: 4000
  playground: true
  cors:
    origin: "*"
    credentials: true
