sources:
  # Core Services
  - name: AuthService
    handler:
      openapi:
        source: http://localhost:5001/swagger/v1/swagger.json
  
  - name: UserService
    handler:
      openapi:
        source: http://localhost:5002/swagger/v1/swagger.json
  
  - name: OrganizationService
    handler:
      openapi:
        source: http://localhost:5003/swagger/v1/swagger.json

  # Business Core Services
  - name: ProductService
    handler:
      openapi:
        source: http://localhost:5004/swagger/v1/swagger.json
  
  - name: CustomerService
    handler:
      openapi:
        source: http://localhost:5005/swagger/v1/swagger.json
  
  - name: TransactionService
    handler:
      openapi:
        source: http://localhost:5006/swagger/v1/swagger.json

  # Business Intelligence Services
  - name: ReportService
    handler:
      openapi:
        source: http://localhost:5007/swagger/v1/swagger.json
  
  - name: NotificationService
    handler:
      openapi:
        source: http://localhost:5008/swagger/v1/swagger.json
  
  - name: FileStorageService
    handler:
      openapi:
        source: http://localhost:5009/swagger/v1/swagger.json

serve:
  port: 4000
  playground: true
  cors:
    origin: "*"
    credentials: true
