sources:
  - name: AuthService
    handler:
      openapi:
        source: http://localhost:5001/swagger/v1/swagger.json
        endpoint: http://localhost:5001
  
  - name: UserService
    handler:
      openapi:
        source: http://localhost:5002/swagger/v1/swagger.json
        endpoint: http://localhost:5002
        operationHeaders:
          Authorization: "{context.headers['authorization']}"
  
  - name: OrganizationService
    handler:
      openapi:
        source: http://localhost:5003/swagger/v1/swagger.json
        endpoint: http://localhost:5003
        operationHeaders:
          Authorization: "{context.headers['authorization']}"
  
  - name: ProductService
    handler:
      openapi:
        source: http://localhost:5004/swagger/v1/swagger.json
        endpoint: http://localhost:5004
        operationHeaders:
          Authorization: "{context.headers['authorization']}"
  
  - name: CustomerService
    handler:
      openapi:
        source: http://localhost:5005/swagger/v1/swagger.json
        endpoint: http://localhost:5005
        operationHeaders:
          Authorization: "{context.headers['authorization']}"
  
  - name: TransactionService
    handler:
      openapi:
        source: http://localhost:5006/swagger/v1/swagger.json
        endpoint: http://localhost:5006
        operationHeaders:
          Authorization: "{context.headers['authorization']}"
  
  - name: ReportService
    handler:
      openapi:
        source: http://localhost:5007/swagger/v1/swagger.json
        endpoint: http://localhost:5007
        operationHeaders:
          Authorization: "{context.headers['authorization']}"
  
  - name: NotificationService
    handler:
      openapi:
        source: http://localhost:5008/swagger/v1/swagger.json
        endpoint: http://localhost:5008
        operationHeaders:
          Authorization: "{context.headers['authorization']}"
  
  - name: FileStorageService
    handler:
      openapi:
        source: http://localhost:5009/swagger/v1/swagger.json
        endpoint: http://localhost:5009
        operationHeaders:
          Authorization: "{context.headers['authorization']}"
  
  - name: SettingsService
    handler:
      openapi:
        source: http://localhost:5010/swagger/v1/swagger.json
        endpoint: http://localhost:5010
        operationHeaders:
          Authorization: "{context.headers['authorization']}"

additionalTypeDefs: |
  type BusinessDashboard {
    todaySales: Float
    totalCustomers: Int
    lowStockCount: Int
    pendingOrders: Int
  }

  type QuickSaleResponse {
    success: Boolean!
    orderId: String
    message: String
  }

  input SaleItemInput {
    productId: String!
    quantity: Int!
    price: Float!
  }

  extend type Query {
    businessDashboard: BusinessDashboard
    healthCheck: String!
  }

  extend type Mutation {
    processQuickSale(
      customerId: String!
      items: [SaleItemInput!]!
      paymentMethod: String!
    ): QuickSaleResponse!
  }

additionalResolvers:
  - ./resolvers/business-aggregates.js
  - ./resolvers/health.js

serve:
  port: 4000
  playground: true
  cors:
    origin: "*"
    credentials: true